title: green Honda
icon: car
capacity: 50 # kWh

## required attributes

soc: # state of charge
  source: const
  value: 42 # %

## optional attributes (read-only)

#limitsoc: # in-vehicle charge limit
#  source: const
#  value: 80 # %
#status: # status [A..F]
#  source: const
#  value: "A"
#range: # range
#  source: const
#  value: 123 # km
#climater: # climate active
#  source: const
#  value: true
#getmaxcurrent: # max charge current
#  source: const
#  value: 16.0 # A
#finishtime: # finish time (RFC3339)
#  source: const
#  value: "2030-01-01T00:00:00Z"

## optional attributes (writeable)

#wakeup: # wake up vehicle
#    source: js
#    script: console.log(wakeup);
#chargeenable: # start/stop charging
#    source: js
#    script: console.log(chargeenable);
#maxcurrent: # set max charge current
#    source: js
#    script: console.log(maxcurrent);

## charging speed-based SoC estimation (for vehicles without SoC reporting)

#chargingSpeedLimit:
#  enabled: false # enable charging speed-based SoC estimation
#  targetSoc: 80 # target SoC percentage to stop charging
#  maxPowerWindow: "10m" # time window to determine max charging power
#  reductionThreshold: 0.15 # power reduction threshold (15%) to trigger estimation
#  minChargingTime: "15m" # minimum charging time before estimation starts
#  sampleInterval: "30s" # how often to sample power
#  historyRetention: "2h" # how long to keep power history
#  stabilityWindow: "5m" # window to check for stable power reduction
#  minPowerForEstimation: 1000 # minimum power (W) to consider for estimation
